package config

import (
	"os"
	"path/filepath"
	"testing"
)

func writeConfig(t *testing.T, dir, content string) {
	t.Helper()
	os.MkdirAll(dir, 0755)
	os.WriteFile(filepath.Join(dir, "config.yaml"), []byte(content), 0644)
}

func TestDefaults(t *testing.T) {
	cfg, err := Load("")
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if cfg.LLM.Type != "openai" {
		t.Errorf("default llm.type = %q, want openai", cfg.LLM.Type)
	}
	if cfg.LLM.MaxTokens != 4096 {
		t.Errorf("default llm.max_tokens = %d, want 4096", cfg.LLM.MaxTokens)
	}
	if cfg.Session.MaxLoop != 50 {
		t.Errorf("default session.max_loop = %d, want 50", cfg.Session.MaxLoop)
	}
	if !cfg.Transport.Stdio.Enabled {
		t.Error("default transport.stdio.enabled = false, want true")
	}
	if !cfg.MCP.Shell.Enabled {
		t.Error("default mcp.shell.enabled = false, want true")
	}
}

func TestLoadConfigFile(t *testing.T) {
	dir := t.TempDir()
	writeConfig(t, dir, `
llm:
  type: "anthropic"
  base_url: "https://api.example.com"
  model: "test-model"
  max_tokens: 2048
session:
  max_loop: 10
transport:
  stdio:
    enabled: false
`)
	orig := ProjectConfigDir
	ProjectConfigDir = dir
	t.Cleanup(func() { ProjectConfigDir = orig })

	cfg, err := Load("")
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if cfg.LLM.Type != "anthropic" {
		t.Errorf("llm.type = %q, want anthropic", cfg.LLM.Type)
	}
	if cfg.LLM.BaseURL != "https://api.example.com" {
		t.Errorf("llm.base_url = %q", cfg.LLM.BaseURL)
	}
	if cfg.LLM.Model != "test-model" {
		t.Errorf("llm.model = %q", cfg.LLM.Model)
	}
	if cfg.LLM.MaxTokens != 2048 {
		t.Errorf("llm.max_tokens = %d, want 2048", cfg.LLM.MaxTokens)
	}
	if cfg.Session.MaxLoop != 10 {
		t.Errorf("session.max_loop = %d, want 10", cfg.Session.MaxLoop)
	}
	if cfg.Transport.Stdio.Enabled {
		t.Error("transport.stdio.enabled = true, want false")
	}
}

func TestEnvOverrides(t *testing.T) {
	dir := t.TempDir()
	writeConfig(t, dir, `
llm:
  type: "anthropic"
  base_url: "https://config.url"
  model: "config-model"
  max_tokens: 1000
`)
	orig := ProjectConfigDir
	ProjectConfigDir = dir
	t.Cleanup(func() { ProjectConfigDir = orig })

	// Set env vars
	os.Setenv("DZ_LLM_TYPE", "openai")
	os.Setenv("DZ_LLM_BASE_URL", "https://env.url")
	os.Setenv("DZ_LLM_MODEL", "env-model")
	os.Setenv("DZ_LLM_API_KEY", "env-key-123")
	os.Setenv("DZ_LLM_MAX_TOKENS", "500")
	t.Cleanup(func() {
		os.Unsetenv("DZ_LLM_TYPE")
		os.Unsetenv("DZ_LLM_BASE_URL")
		os.Unsetenv("DZ_LLM_MODEL")
		os.Unsetenv("DZ_LLM_API_KEY")
		os.Unsetenv("DZ_LLM_MAX_TOKENS")
	})

	cfg, err := Load("")
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if cfg.LLM.Type != "openai" {
		t.Errorf("llm.type = %q, want openai", cfg.LLM.Type)
	}
	if cfg.LLM.BaseURL != "https://env.url" {
		t.Errorf("llm.base_url = %q, want https://env.url", cfg.LLM.BaseURL)
	}
	if cfg.LLM.Model != "env-model" {
		t.Errorf("llm.model = %q, want env-model", cfg.LLM.Model)
	}
	if cfg.LLM.APIKey != "env-key-123" {
		t.Errorf("llm.api_key = %q, want env-key-123", cfg.LLM.APIKey)
	}
	if cfg.LLM.MaxTokens != 500 {
		t.Errorf("llm.max_tokens = %d, want 500", cfg.LLM.MaxTokens)
	}
}

func TestEnvOverrideEmptyDoesNotOverride(t *testing.T) {
	dir := t.TempDir()
	writeConfig(t, dir, `
llm:
  type: "anthropic"
  base_url: "https://config.url"
  model: "config-model"
`)
	orig := ProjectConfigDir
	ProjectConfigDir = dir
	t.Cleanup(func() { ProjectConfigDir = orig })

	// Set only the API key env, leave others unset
	os.Setenv("DZ_LLM_API_KEY", "test-key")
	t.Cleanup(func() { os.Unsetenv("DZ_LLM_API_KEY") })

	cfg, err := Load("")
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if cfg.LLM.Type != "anthropic" {
		t.Errorf("llm.type = %q, want anthropic (should not be overridden)", cfg.LLM.Type)
	}
	if cfg.LLM.BaseURL != "https://config.url" {
		t.Errorf("llm.base_url = %q, want https://config.url", cfg.LLM.BaseURL)
	}
	if cfg.LLM.APIKey != "test-key" {
		t.Errorf("llm.api_key = %q, want test-key", cfg.LLM.APIKey)
	}
}

func TestSessionDirDefault(t *testing.T) {
	cfg, err := Load("")
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if cfg.Session.Dir == "" {
		t.Error("session.dir should have a default")
	}
}

func TestSSHDefaults(t *testing.T) {
	cfg, err := Load("")
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if cfg.Transport.SSH.Username != "dolphinzZ" {
		t.Errorf("ssh.username = %q, want dolphinzZ", cfg.Transport.SSH.Username)
	}
	if cfg.Transport.SSH.Addr != ":2222" {
		t.Errorf("ssh.addr = %q, want :2222", cfg.Transport.SSH.Addr)
	}
}

func TestSSHPasswordNotAutoGeneratedWhenDisabled(t *testing.T) {
	dir := t.TempDir()
	writeConfig(t, dir, `
transport:
  ssh:
    enabled: false
`)
	orig := ProjectConfigDir
	ProjectConfigDir = dir
	t.Cleanup(func() { ProjectConfigDir = orig })

	cfg, err := Load("")
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	// Password should still be empty because SSH is disabled
	if cfg.Transport.SSH.Password != "" {
		t.Log("password was auto-generated despite SSH being disabled")
	}
}

func TestSSHPasswordAutoGeneratedWhenEnabled(t *testing.T) {
	dir := t.TempDir()
	writeConfig(t, dir, `
transport:
  ssh:
    enabled: true
`)
	orig := ProjectConfigDir
	ProjectConfigDir = dir
	t.Cleanup(func() { ProjectConfigDir = orig })

	cfg, err := Load("")
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if cfg.Transport.SSH.Password == "" {
		t.Fatal("expected auto-generated password for enabled SSH")
	}
	if len(cfg.Transport.SSH.Password) < 8 {
		t.Errorf("password too short: %q (len=%d)", cfg.Transport.SSH.Password, len(cfg.Transport.SSH.Password))
	}
}

func TestSSHPasswordPersistsAcrossLoads(t *testing.T) {
	dir := t.TempDir()
	writeConfig(t, dir, `
transport:
  ssh:
    enabled: true
`)
	orig := ProjectConfigDir
	ProjectConfigDir = dir
	t.Cleanup(func() { ProjectConfigDir = orig })

	cfg1, err := Load("")
	if err != nil {
		t.Fatalf("first Load() error: %v", err)
	}
	if cfg1.Transport.SSH.Password == "" {
		t.Fatal("first load: expected auto-generated password")
	}

	// Load again — should reuse persisted password
	cfg2, err := Load("")
	if err != nil {
		t.Fatalf("second Load() error: %v", err)
	}
	if cfg2.Transport.SSH.Password != cfg1.Transport.SSH.Password {
		t.Errorf("password changed between loads: %q -> %q", cfg1.Transport.SSH.Password, cfg2.Transport.SSH.Password)
	}
}

func TestSSHPasswordFromConfig(t *testing.T) {
	dir := t.TempDir()
	writeConfig(t, dir, `
transport:
  ssh:
    enabled: true
    password: "mypassword"
`)
	orig := ProjectConfigDir
	ProjectConfigDir = dir
	t.Cleanup(func() { ProjectConfigDir = orig })

	cfg, err := Load("")
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if cfg.Transport.SSH.Password != "mypassword" {
		t.Errorf("password = %q, want mypassword", cfg.Transport.SSH.Password)
	}
}

func TestMaxContextTokensDefault(t *testing.T) {
	cfg, err := Load("")
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if cfg.LLM.MaxContextTokens != 1048576 {
		t.Errorf("max_context_tokens = %d, want 1048576", cfg.LLM.MaxContextTokens)
	}
}
